# Generated by Django 4.2.7 on 2023-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userform_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userform',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
